### PR TITLE
Add parent pointer to Node

### PR DESCRIPTION
**Pull request by dmac**

### CODE REVIEW

**Comment by cespare** [comment]
@dmac looking at this now, it seems like a really error-prone API. Almost any use of `SetParent` breaks the coherence of tree structure and requires one or more `SetChildren` calls to fix it up. However, I don't think we actually need to expose `SetParent`, only the getter -- correct?

Furthermore, ISTM that `SetChildren` should ensure that the parent pointers are updated. For maximum defensiveness, I think it should call `setParent(nil)` on all the old children and then `setParent(node)` on all the new children.

WDYT? Possibly I'm missing something because it has been a while since I thought about this.

**Comment by dmac** [comment]
I think that makes sense. I unexported `setParent` and updated `SetChildren` as you suggested. I suppose the main reason `SetChildren` is exported is to support formatting?

**Review by cespare — APPROVED** [review]
> I think that makes sense. I unexported `setParent` and updated `SetChildren` as you suggested. I suppose the main reason `SetChildren` is exported is to support formatting?

What do you mean by "support formatting"?

**Comment by dmac** [comment]
> What do you mean by "support formatting"?

SetChildren needs to be exported because it's used by the goclj/format package. I'm curious if that's the only reason it's exported, or if the intent is to allow external users to manipulate the parse tree as well.

**Pull request merged**
